/**********************************************************************************************************************
 * \file shared.h
 * \copyright Copyright (C) Infineon Technologies AG 2024
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef SHARED_H
#define SHARED_H

#if defined(__cplusplus)
extern "C" {
#endif

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Values used on g_shared */
enum
{
    IDLE = 0,
    FROM_CM0_CM7_0_READ_TEST0_ADDR,
	FROM_CM0_CM7_0_READ_TEST1_ADDR,
	FROM_CM0_CM7_1_READ_TEST0_ADDR,
	FROM_CM0_CM7_1_READ_TEST1_ADDR,
    FROM_CM7_PENDING_ANSWER,
};

#if defined(COMPONENT_CAT1C8M)
/* Region 2 Start Address */
#define TEST0_ADDR (0x28001000ul)
/* Region 3 Start Address */
#define TEST1_ADDR (0x28002000ul)
#endif
#if defined(COMPONENT_TVIIC2D6M)
/* Region 2 Start Address */
#define TEST0_ADDR (0x28080000ul)
/* Region 3 Start Address */
#define TEST1_ADDR (0x28081000ul)
#endif


/* Sleep time between processing */
#define SLEEP_TIME_MS   100

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Variable used as shared memory in each core */
CY_SECTION(".shared") uint32_t g_shared[2];

#if defined(__cplusplus)
}
#endif

#endif /* SHARED_H */
/* [] END OF FILE */
